### PR TITLE
bitcoin farm calculator

### PR DESCRIPTION
**Pull request by Gyran**
Not ready yet, but opening a PR so I can use netlify to show it :)

https://deploy-preview-154--tarkov-tools-preview.netlify.app/btc-farm-calculator

TODOs
* [x] use solar power from settings

### CODE REVIEW

**Comment by kokarn** [comment]
Things I think should be included:
* Bitcoinc price
* Graphics card price

Suggestions I've seen in different places:
* Include fuel cost
* Include Solar toggle/calculation

**Comment by kokarn** [comment]
Another nice to have: cost of building things. Like Bitcoin farm 2

**Comment by Gyran** [comment]
Added fuel price etc to the calculations now and btc farm hardly profitable unless you have everything maxed out and solar power. So adding cost of buying the actual farm (and solar power) as well would just make it seem even less profitable. But that's when you look at it only as a single unit. Hopefully you do more than just creating bitcoins with your fuel so it's probably positive to use it anyway even thought on its own it's kind of useless.. 

For the fuel cost, I just use metal fuel tank as it's the cheapest but I guess we could make it selectable as well but I don't see the use for that. Maybe just always get the cheapest fuel cost.

What do you think?

**Comment by Gyran** [comment]
I think it has the features "I" need so will probably not do so much more than this if anyone dosen't object loudly. Guess it can do with a bit of styling to look nicer. But otherwise it's usable :P
If you think it's not complete enough for a merge that's fine, i can use netlify to get what I want :D

**Pull request merged**
