### PR TITLE
add settings toggle to hide remote control

### PR DESCRIPTION
**Pull request by Gyran**

### CODE REVIEW

**Comment by kokarn** [comment]
.... why is this not auto-building? 🤔

**Comment by Gyran** [comment]
some setting missing? seems like https://github.com/kokarn/tarkov-tools/pull/151 isn't building either..

**Comment by kokarn** [comment]
Doesn't even run lint it seems

**Comment by Gyran** [comment]
https://www.githubstatus.com/ github actions has some problems, and webhooks so could be related to that

**Comment by kokarn** [comment]
Yeah looked good as late as yesterday 
image

**Comment by kokarn** [comment]
I didn't get an email for #151 and the merge for it hasn't deployed. So I guess I'll wait and see :)

**Pull request merged**
