### PR TITLE
Add hideout managment skill

### PR DESCRIPTION
**Pull request by Akiyamov**
Skill reducing filter count for purified water by 0.5 each level. I made it fixed to 2 digits after float so it's not that accurate but still working. Also added author [of this pr](https://github.com/kokarn/tarkov-tools/pull/102) in footer.

Solves: [https://github.com/kokarn/tarkov-tools/issues/90](#90)

### CODE REVIEW

**Comment by Akiyamov** [comment]
Nearly forgot about seconds which i reverted. I added them because sometimes craft reduction time can be really confusing without them

**Comment by Akiyamov** [comment]
Don't add this pr, just saw that my way of changing the count breaks barters-table :/

**Comment by kokarn** [comment]
Looks good overall! Excellent work!
I'll fix the tests when this is merged so it doesn't mess up the display of the whole PR :)

Is this ready to merge now?

**Comment by Akiyamov** [comment]
Barter table is loading, both in barter and item pages, so i think it's fine. If you're trying to accesses item page and it gives you "TypeError: questData.giver is undefined" because it's required for quest it's problem of local server since on main branch me and my friend got this error.

**Comment by kokarn** [comment]
Cool! Yeah, I think that's because the data needs to be re-added by running the pre-install script.

I'll have a look at that tomorrow as well 👍 

Thanks for these great PRs!

**Pull request merged**
